---
Organizations:
  - &claim-com
      Name: claim-com
      ID: claim-com
      MSPDir: keyfiles/ordererOrganizations/claim.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('claim-com.member')"
        Writers:
          Type: Signature
          Rule: "OR('claim-com.member')"
        Admins:
          Type: Signature
          Rule: "OR('claim-com.admin')"
  - &governmentagency-claim-com
      Name: governmentagency-claim-com
      ID: governmentagency-claim-com
      MSPDir: keyfiles/peerOrganizations/governmentagency.claim.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('governmentagency-claim-com.admin', 'governmentagency-claim-com.peer', 'governmentagency-claim-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('governmentagency-claim-com.admin', 'governmentagency-claim-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('governmentagency-claim-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('governmentagency-claim-com.peer')"

      AnchorPeers:
      - Host: 192.168.29.146
        Port: 7005
  - &insurancecompany-claim-com
      Name: insurancecompany-claim-com
      ID: insurancecompany-claim-com
      MSPDir: keyfiles/peerOrganizations/insurancecompany.claim.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('insurancecompany-claim-com.admin', 'insurancecompany-claim-com.peer', 'insurancecompany-claim-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('insurancecompany-claim-com.admin', 'insurancecompany-claim-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('insurancecompany-claim-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('insurancecompany-claim-com.peer')"

      AnchorPeers:
      - Host: 192.168.29.146
        Port: 7006
  - &policedepartment-claim-com
      Name: policedepartment-claim-com
      ID: policedepartment-claim-com
      MSPDir: keyfiles/peerOrganizations/policedepartment.claim.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('policedepartment-claim-com.admin', 'policedepartment-claim-com.peer', 'policedepartment-claim-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('policedepartment-claim-com.admin', 'policedepartment-claim-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('policedepartment-claim-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('policedepartment-claim-com.peer')"

      AnchorPeers:
      - Host: 192.168.29.146
        Port: 7004
  - &vehiclemanufacturer-claim-com
      Name: vehiclemanufacturer-claim-com
      ID: vehiclemanufacturer-claim-com
      MSPDir: keyfiles/peerOrganizations/vehiclemanufacturer.claim.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('vehiclemanufacturer-claim-com.admin', 'vehiclemanufacturer-claim-com.peer', 'vehiclemanufacturer-claim-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('vehiclemanufacturer-claim-com.admin', 'vehiclemanufacturer-claim-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('vehiclemanufacturer-claim-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('vehiclemanufacturer-claim-com.peer')"

      AnchorPeers:
      - Host: 192.168.29.146
        Port: 7007

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Addresses:
  - 192.168.29.146:7012
  - 192.168.29.146:7013
  - 192.168.29.146:7014
  - 192.168.29.146:7015
  EtcdRaft:
    Consenters:
    - Host: 192.168.29.146
      Port: 7012
      ClientTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer1.claim.com/tls/server.crt
      ServerTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer1.claim.com/tls/server.crt
    - Host: 192.168.29.146
      Port: 7013
      ClientTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer2.claim.com/tls/server.crt
      ServerTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer2.claim.com/tls/server.crt
    - Host: 192.168.29.146
      Port: 7014
      ClientTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer3.claim.com/tls/server.crt
      ServerTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer3.claim.com/tls/server.crt
    - Host: 192.168.29.146
      Port: 7015
      ClientTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer4.claim.com/tls/server.crt
      ServerTLSCert: keyfiles/ordererOrganizations/claim.com/orderers/orderer4.claim.com/tls/server.crt
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrgChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *governmentagency-claim-com
      - *insurancecompany-claim-com
      - *policedepartment-claim-com
      - *vehiclemanufacturer-claim-com
      Capabilities:
        <<: *ApplicationCapabilities

  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *claim-com
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - <<: *claim-com
    Consortiums:
      SampleConsortium:
        Organizations:
        - *governmentagency-claim-com
        - *insurancecompany-claim-com
        - *policedepartment-claim-com
        - *vehiclemanufacturer-claim-com
